version: '3'
services:
  auth:
    container_name: auth-container
    restart: always
    depends_on:
      - db
    build: ./auth
    environment:
      DB_HOST: db
      DB_USER: msaleh
      DB_PASSWORD: 123456
      DB_NAME: weather-app-db
    # ports:
    #   - 8080
    networks:
      - weather-network

  ui:
    container_name: ui-website-container
    build: ./UI
    depends_on:
      - auth
      - weather
    restart: always
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
    ports:
      - "8080:3000"
    networks:
      - weather-network

  weather:
    container_name: weather-container
    restart: always
    build: ./weather
    environment:
      APIKEY: 6d92c50bdamsh81137f3b87ace1fp1d53eejsnfe818b9dbc83
    # ports:
    #   - 5000
    networks:
      - weather-network

  db:
    container_name: db-container
    restart: always
    image: mysql:8.0.25
    environment:
    - MYSQL_DATABASE= db
    - MYSQL_ROOT_PASSWORD= 123456
    networks:
      - weather-network
    volumes:
      - ./database:/var/lib/mysql

networks:
  weather-network:
    driver: bridge